package pizzagame;
import java.io.IOException;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JOptionPane;
/**
 *
 * @author r.stuchevsky
 */
public class Menu extends javax.swing.JFrame {
    /**
     * Creates new form Menu
     */
    public Menu() throws UnsupportedAudioFileException, IOException, LineUnavailableException {
        this.setVisible(true);
        initComponents();
        this.setSize(720,720);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        btnInfo = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/giphy.gif"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 90, 380, 460);

        jLabel2.setFont(new java.awt.Font("Rockwell", 0, 48)); // NOI18N
        jLabel2.setText("Papa's Pizzeria");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, -30, 360, 132);

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        getContentPane().add(btnStart);
        btnStart.setBounds(120, 590, 110, 40);

        btnInfo.setText("Instructions");
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });
        getContentPane().add(btnInfo);
        btnInfo.setBounds(290, 590, 110, 40);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(460, 590, 110, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Starts up the game and minimizes this menu
     * @param evt 
     */
    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        this.setVisible(false);
        UI ui = new UI();
    }//GEN-LAST:event_btnStartActionPerformed
    /**
     * Exits the game completly
     * @param evt 
     */
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed
    /**
     * Display the info
     * @param evt 
     */
    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
       JOptionPane.showMessageDialog(null,"Welcome to the Papa's Pizzeria!" + "\n" + 
               "The Game is simple, you have 25 seconds to build a customer order exactly to the T." + "\n" + 
               "Click the buttons to add ingridients to your order, than 'finish order' to hand it to the customer." + 
               "\n" + "If you ran out of time or your order was incorrect you lose a heart" + "\n" + 
               "Once you lost all three of your hearts its game over."+ "\n" + "Your money and customer "
               + "highscore will be saved for your next restart" + "\n" + "Good Luck and have fun!");
    }//GEN-LAST:event_btnInfoActionPerformed

   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
