package pizzagame;
import Tools.FileHandler;
import Tools.GameImage;
import Tools.MediaPlayer;
import collections.LinkedList;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import static pizzagame.PizzaOrder.cheeseTypes;
import static pizzagame.PizzaOrder.doughTypes;
import static pizzagame.PizzaOrder.sauceTypes;
import static pizzagame.PizzaOrder.toppingTypes;

/**
 *UI and code for the pizza game that allows the user to play pizza game 
 * @Instructor Mr.Wachs
 * @since 10-May-2019 
 * @author r.stuchevsky
 */
public class UI extends javax.swing.JFrame {
    //propeties of the class
    public LinkedList<String> order; // the customer order
    public LinkedList<String> userList = new LinkedList<>(); //the user order that will be filled
    private int time = 25; // the starting amount of time
    private int money = 3;  // the starting amount of money
    public int served = 0; // number of served cutomers updates with each succesful serve
    private int lives = 3;  //number of lives (if 3 are gone its game over)
    private Customer customer = new Customer();
    private Timer timer;
    private FileHandler file;
    private MediaPlayer mediaPlayer = new MediaPlayer();
    private GameImage image;
    /**
     * Deafult constructor of the class sets class properties
     */
    public UI() {
        initComponents();
        file = new FileHandler("/pizzagame/data.txt");
        String[] data = file.read();
        if (data != null) {
            String text = "Last High Score was: " + "\n" + "Money Earned = " + data[0] + "\n"
                    + "Customers Served = " + data[1];
            JOptionPane.showMessageDialog(this, text);
        }
        name();
        backgroundCheck();
        timer.start();
        order = customer.order(doughTypes, sauceTypes, cheeseTypes, toppingTypes);
        lblOrder.setText(order.toString(order));
        lblServed.setText("Served: " + served);
        image = new GameImage(lblPic);
         mediaPlayer.playWAV("/media/BackgroundMusic.wav"); 
        this.setSize(915, 700);
        this.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblOrder = new javax.swing.JLabel();
        lblPic = new javax.swing.JLabel();
        btnDoughFull = new javax.swing.JButton();
        btnDoughThick = new javax.swing.JButton();
        btnDoughThin = new javax.swing.JButton();
        btnDoughSoft = new javax.swing.JButton();
        btnDoughItalian = new javax.swing.JButton();
        btnSauceItalian = new javax.swing.JButton();
        btnSauceHomeMade = new javax.swing.JButton();
        btnSauceAmerican = new javax.swing.JButton();
        btnSauceSpicy = new javax.swing.JButton();
        btnSauceLouisiana = new javax.swing.JButton();
        btnCheeseMozz = new javax.swing.JButton();
        btnCheeseSwiss = new javax.swing.JButton();
        btnCheeseOld = new javax.swing.JButton();
        btnCheeseCheddar = new javax.swing.JButton();
        btnCheeseProvolone = new javax.swing.JButton();
        btnTopPeperoni = new javax.swing.JButton();
        btnTopHam = new javax.swing.JButton();
        btnTopSalami = new javax.swing.JButton();
        btnTopPineApple = new javax.swing.JButton();
        btnTopMushroom = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblResponse = new javax.swing.JLabel();
        lblTimer = new javax.swing.JLabel();
        txtName = new javax.swing.JLabel();
        lblTxt = new javax.swing.JLabel();
        lblMoney = new javax.swing.JLabel();
        btnDoughCheese = new javax.swing.JButton();
        btnSauceChipotle = new javax.swing.JButton();
        btnCheeseParmesan = new javax.swing.JButton();
        btnTopPepper = new javax.swing.JButton();
        btnDone = new javax.swing.JButton();
        lblDisMoney = new javax.swing.JLabel();
        lblHeart3 = new javax.swing.JLabel();
        lblHeart1 = new javax.swing.JLabel();
        lblHeart2 = new javax.swing.JLabel();
        lblServed = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Papa Jhon's Pizzeria Tycoon");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        lblOrder.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblOrder.setText("order");
        getContentPane().add(lblOrder);
        lblOrder.setBounds(20, 260, 860, 50);
        getContentPane().add(lblPic);
        lblPic.setBounds(20, 30, 290, 230);

        btnDoughFull.setText("Full Grain");
        btnDoughFull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoughFullActionPerformed(evt);
            }
        });
        getContentPane().add(btnDoughFull);
        btnDoughFull.setBounds(110, 340, 100, 23);

        btnDoughThick.setText("Thick");
        btnDoughThick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoughThickActionPerformed(evt);
            }
        });
        getContentPane().add(btnDoughThick);
        btnDoughThick.setBounds(110, 380, 100, 23);

        btnDoughThin.setText("Thin");
        btnDoughThin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoughThinActionPerformed(evt);
            }
        });
        getContentPane().add(btnDoughThin);
        btnDoughThin.setBounds(110, 420, 100, 23);

        btnDoughSoft.setText("Soft");
        btnDoughSoft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoughSoftActionPerformed(evt);
            }
        });
        getContentPane().add(btnDoughSoft);
        btnDoughSoft.setBounds(110, 460, 100, 23);

        btnDoughItalian.setText("Italian");
        btnDoughItalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoughItalianActionPerformed(evt);
            }
        });
        getContentPane().add(btnDoughItalian);
        btnDoughItalian.setBounds(110, 500, 100, 23);

        btnSauceItalian.setText("Italian");
        btnSauceItalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSauceItalianActionPerformed(evt);
            }
        });
        getContentPane().add(btnSauceItalian);
        btnSauceItalian.setBounds(240, 340, 110, 23);

        btnSauceHomeMade.setText("HomeMade");
        btnSauceHomeMade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSauceHomeMadeActionPerformed(evt);
            }
        });
        getContentPane().add(btnSauceHomeMade);
        btnSauceHomeMade.setBounds(240, 380, 110, 23);

        btnSauceAmerican.setText("American");
        btnSauceAmerican.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSauceAmericanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSauceAmerican);
        btnSauceAmerican.setBounds(240, 420, 110, 23);

        btnSauceSpicy.setText("Spicy");
        btnSauceSpicy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSauceSpicyActionPerformed(evt);
            }
        });
        getContentPane().add(btnSauceSpicy);
        btnSauceSpicy.setBounds(240, 460, 110, 23);

        btnSauceLouisiana.setText("Louisiana");
        btnSauceLouisiana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSauceLouisianaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSauceLouisiana);
        btnSauceLouisiana.setBounds(240, 500, 110, 23);

        btnCheeseMozz.setText("Mozzarella");
        btnCheeseMozz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheeseMozzActionPerformed(evt);
            }
        });
        getContentPane().add(btnCheeseMozz);
        btnCheeseMozz.setBounds(370, 340, 100, 23);

        btnCheeseSwiss.setText("Swiss");
        btnCheeseSwiss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheeseSwissActionPerformed(evt);
            }
        });
        getContentPane().add(btnCheeseSwiss);
        btnCheeseSwiss.setBounds(370, 380, 100, 23);

        btnCheeseOld.setText("OldFort");
        btnCheeseOld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheeseOldActionPerformed(evt);
            }
        });
        getContentPane().add(btnCheeseOld);
        btnCheeseOld.setBounds(370, 420, 100, 23);

        btnCheeseCheddar.setText("Cheddar");
        btnCheeseCheddar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheeseCheddarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCheeseCheddar);
        btnCheeseCheddar.setBounds(370, 460, 100, 23);

        btnCheeseProvolone.setText("Provolone");
        btnCheeseProvolone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheeseProvoloneActionPerformed(evt);
            }
        });
        getContentPane().add(btnCheeseProvolone);
        btnCheeseProvolone.setBounds(370, 500, 100, 23);

        btnTopPeperoni.setText("Peperoni");
        btnTopPeperoni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopPeperoniActionPerformed(evt);
            }
        });
        getContentPane().add(btnTopPeperoni);
        btnTopPeperoni.setBounds(500, 340, 110, 23);

        btnTopHam.setText("Ham");
        btnTopHam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopHamActionPerformed(evt);
            }
        });
        getContentPane().add(btnTopHam);
        btnTopHam.setBounds(500, 380, 110, 23);

        btnTopSalami.setText("Salami");
        btnTopSalami.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopSalamiActionPerformed(evt);
            }
        });
        getContentPane().add(btnTopSalami);
        btnTopSalami.setBounds(500, 420, 110, 23);

        btnTopPineApple.setText("Pineapple");
        btnTopPineApple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopPineAppleActionPerformed(evt);
            }
        });
        getContentPane().add(btnTopPineApple);
        btnTopPineApple.setBounds(500, 460, 110, 23);

        btnTopMushroom.setText("Mushrooms");
        btnTopMushroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopMushroomActionPerformed(evt);
            }
        });
        getContentPane().add(btnTopMushroom);
        btnTopMushroom.setBounds(500, 500, 110, 23);

        jLabel3.setText("Toppings");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(500, 320, 70, 20);

        jLabel4.setText("Doughs");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 320, 70, 20);

        jLabel5.setText("Sauces");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(240, 320, 70, 20);

        jLabel6.setText("Cheeses");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(370, 320, 70, 20);

        lblResponse.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblResponse.setText("Response of customer");
        getContentPane().add(lblResponse);
        lblResponse.setBounds(30, 590, 570, 90);

        lblTimer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTimer.setText("25");
        getContentPane().add(lblTimer);
        lblTimer.setBounds(440, 40, 30, 20);
        lblTimer.getAccessibleContext().setAccessibleName("");

        txtName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtName.setText("PlayerName");
        getContentPane().add(txtName);
        txtName.setBounds(570, 50, 110, 50);

        lblTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTxt.setText("Time Left:");
        getContentPane().add(lblTxt);
        lblTxt.setBounds(410, 10, 90, 30);

        lblMoney.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMoney.setText("Money");
        getContentPane().add(lblMoney);
        lblMoney.setBounds(570, 100, 90, 30);

        btnDoughCheese.setText("Cheese Fill");
        btnDoughCheese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoughCheeseActionPerformed(evt);
            }
        });
        getContentPane().add(btnDoughCheese);
        btnDoughCheese.setBounds(110, 540, 100, 23);

        btnSauceChipotle.setText("Chipotle");
        btnSauceChipotle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSauceChipotleActionPerformed(evt);
            }
        });
        getContentPane().add(btnSauceChipotle);
        btnSauceChipotle.setBounds(240, 540, 110, 23);

        btnCheeseParmesan.setText("Parmesan");
        btnCheeseParmesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheeseParmesanActionPerformed(evt);
            }
        });
        getContentPane().add(btnCheeseParmesan);
        btnCheeseParmesan.setBounds(370, 540, 100, 23);

        btnTopPepper.setText("Peppers");
        btnTopPepper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopPepperActionPerformed(evt);
            }
        });
        getContentPane().add(btnTopPepper);
        btnTopPepper.setBounds(500, 540, 110, 23);

        btnDone.setText("Finish Order");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });
        getContentPane().add(btnDone);
        btnDone.setBounds(670, 630, 120, 23);

        lblDisMoney.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(lblDisMoney);
        lblDisMoney.setBounds(640, 100, 80, 30);

        lblHeart3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/heart.png"))); // NOI18N
        getContentPane().add(lblHeart3);
        lblHeart3.setBounds(800, 190, 70, 70);

        lblHeart1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/heart.png"))); // NOI18N
        getContentPane().add(lblHeart1);
        lblHeart1.setBounds(800, 10, 70, 70);

        lblHeart2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/heart.png"))); // NOI18N
        getContentPane().add(lblHeart2);
        lblHeart2.setBounds(800, 100, 70, 70);

        lblServed.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblServed.setText("Served: 0");
        getContentPane().add(lblServed);
        lblServed.setBounds(570, 140, 90, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Adds pizza ingredients to the User Linked List
     * @param evt 
     */
    private void btnDoughFullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoughFullActionPerformed
        mediaPlayer.playWAV("/media/ButtonSound.wav"); 
        userList.add(doughTypes.get(0));
        image.setImage("/media/PizzaDough.png");
    }//GEN-LAST:event_btnDoughFullActionPerformed
    /**
     * Adds pizza ingredients to the User Linked List
     * @param evt 
     */
    private void btnCheeseOldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheeseOldActionPerformed
        mediaPlayer.playWAV("/media/ButtonSound.wav"); 
        userList.add(cheeseTypes.get(2));
        image.setImage("/media/PizzaCheese.png");
    }//GEN-LAST:event_btnCheeseOldActionPerformed
    /**
     * Adds pizza ingredients to the User Linked List
     * @param evt 
     */
    private void btnTopPineAppleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopPineAppleActionPerformed
        mediaPlayer.playWAV("/media/ButtonSound.wav"); 
        userList.add(toppingTypes.get(3));
        image.setImage("/media/PizzaPineApple.png");  
    }//GEN-LAST:event_btnTopPineAppleActionPerformed
    /**
     * Adds pizza ingredients to the User Linked List
     * @param evt 
     */
    private void btnTopMushroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopMushroomActionPerformed
        mediaPlayer.playWAV("/media/ButtonSound.wav"); 
        userList.add(toppingTypes.get(4));
        image.setImage("/media/PizzaMushroom.png");  
    }//GEN-LAST:event_btnTopMushroomActionPerformed
    /**
     * Adds pizza ingredients to the User Linked List
     * @param evt 
     */
    private void btnTopPepperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopPepperActionPerformed
        mediaPlayer.playWAV("/media/ButtonSound.wav"); 
        userList.add(toppingTypes.get(5));
        image.setImage("/media/PizzaPeppers.png"); 
    }//GEN-LAST:event_btnTopPepperActionPerformed
    /**
     * Adds pizza ingredients to the User Linked List
     * @param evt 
     */
    private void btnSauceChipotleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSauceChipotleActionPerformed
        mediaPlayer.playWAV("/media/ButtonSound.wav"); 
        userList.add(sauceTypes.get(5));
        image.setImage("/media/PizzaSauce.png"); 
    }//GEN-LAST:event_btnSauceChipotleActionPerformed
    /**
     * Adds pizza ingredients to the User Linked List
     * @param evt 
     */
    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
         mediaPlayer.playWAV("/media/ButtonSound.wav"); 
        checkOrder(order, userList);
         image.setClear();
    }//GEN-LAST:event_btnDoneActionPerformed
     /**
     * Adds pizza ingredients to the User Linked List
     * @param evt 
     */
    private void btnDoughThickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoughThickActionPerformed
        mediaPlayer.playWAV("/media/ButtonSound.wav"); 
        userList.add(doughTypes.get(1));
        image.setImage("/media/PizzaDough.png");  
    }//GEN-LAST:event_btnDoughThickActionPerformed
    /**
     * Adds pizza ingredients to the User Linked List
     * @param evt 
     */
    private void btnDoughThinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoughThinActionPerformed
        mediaPlayer.playWAV("/media/ButtonSound.wav"); 
        userList.add(doughTypes.get(2));
        image.setImage("/media/PizzaDough.png");
    }//GEN-LAST:event_btnDoughThinActionPerformed
    /**
     * Adds pizza ingredients to the User Linked List
     * @param evt 
     */
    private void btnDoughSoftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoughSoftActionPerformed
       mediaPlayer.playWAV("/media/ButtonSound.wav"); 
        userList.add(doughTypes.get(3));
        image.setImage("/media/PizzaDough.png");
    }//GEN-LAST:event_btnDoughSoftActionPerformed
    /**
     * Adds pizza ingredients to the User Linked List
     * @param evt 
     */
    private void btnDoughItalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoughItalianActionPerformed
        mediaPlayer.playWAV("/media/ButtonSound.wav"); 
        userList.add(doughTypes.get(4));
        image.setImage("/media/PizzaDough.png");
    }//GEN-LAST:event_btnDoughItalianActionPerformed
    /**
     * Adds pizza ingredients to the User Linked List
     * @param evt 
     */
    private void btnDoughCheeseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoughCheeseActionPerformed
        mediaPlayer.playWAV("/media/ButtonSound.wav"); 
        userList.add(doughTypes.get(5));
        image.setImage("/media/PizzaDough.png");
    }//GEN-LAST:event_btnDoughCheeseActionPerformed
    /**
     * Adds pizza ingredients to the User Linked List
     * @param evt 
     */
    private void btnSauceItalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSauceItalianActionPerformed
        mediaPlayer.playWAV("/media/ButtonSound.wav"); 
        userList.add(sauceTypes.get(0));
        image.setImage("/media/PizzaSauce.png");
    }//GEN-LAST:event_btnSauceItalianActionPerformed
    /**
     * Adds pizza ingredients to the User Linked List
     * @param evt 
     */
    private void btnSauceHomeMadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSauceHomeMadeActionPerformed
        mediaPlayer.playWAV("/media/ButtonSound.wav"); 
        userList.add(sauceTypes.get(1));
        image.setImage("/media/PizzaSauce.png");
    }//GEN-LAST:event_btnSauceHomeMadeActionPerformed
    /**
     * Adds pizza ingredients to the User Linked List
     * @param evt 
     */
    private void btnSauceAmericanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSauceAmericanActionPerformed
        mediaPlayer.playWAV("/media/ButtonSound.wav"); 
        userList.add(sauceTypes.get(2));
        image.setImage("/media/PizzaSauce.png"); 
    }//GEN-LAST:event_btnSauceAmericanActionPerformed
    /**
     * Adds pizza ingredients to the User Linked List
     * @param evt 
     */
    private void btnSauceSpicyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSauceSpicyActionPerformed
        mediaPlayer.playWAV("/media/ButtonSound.wav"); 
        userList.add(sauceTypes.get(3));
        image.setImage("/media/PizzaSauce.png");
    }//GEN-LAST:event_btnSauceSpicyActionPerformed
    /**
     * Adds pizza ingredients to the User Linked List
     * @param evt 
     */
    private void btnSauceLouisianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSauceLouisianaActionPerformed
        mediaPlayer.playWAV("/media/ButtonSound.wav"); 
        userList.add(sauceTypes.get(4));
        image.setImage("/media/PizzaSauce.png");
    }//GEN-LAST:event_btnSauceLouisianaActionPerformed
    /**
     * Adds pizza ingredients to the User Linked List
     * @param evt 
     */
    private void btnCheeseMozzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheeseMozzActionPerformed
        mediaPlayer.playWAV("/media/ButtonSound.wav"); 
        image.setImage("/media/PizzaCheese.png");
        userList.add(cheeseTypes.get(0)); 
    }//GEN-LAST:event_btnCheeseMozzActionPerformed
     /**
     * Adds pizza ingredients to the User Linked List
     * @param evt 
     */
    private void btnCheeseSwissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheeseSwissActionPerformed
        mediaPlayer.playWAV("/media/ButtonSound.wav"); 
        image.setImage("/media/PizzaCheese.png");
        userList.add(cheeseTypes.get(1)); 
    }//GEN-LAST:event_btnCheeseSwissActionPerformed
    /**
     * Adds pizza ingredients to the User Linked List
     * @param evt 
     */
    private void btnCheeseCheddarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheeseCheddarActionPerformed
        mediaPlayer.playWAV("/media/ButtonSound.wav"); 
        image.setImage("/media/PizzaCheese.png");
        userList.add(cheeseTypes.get(3));
    }//GEN-LAST:event_btnCheeseCheddarActionPerformed
    /**
     * Adds pizza ingredients to the User Linked List
     * @param evt 
     */
    private void btnCheeseProvoloneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheeseProvoloneActionPerformed
        mediaPlayer.playWAV("/media/ButtonSound.wav"); 
        image.setImage("/media/PizzaCheese.png");
        userList.add(cheeseTypes.get(4));
    }//GEN-LAST:event_btnCheeseProvoloneActionPerformed
    /**
     * Adds pizza ingredients to the User Linked List
     * @param evt 
     */
    private void btnCheeseParmesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheeseParmesanActionPerformed
         mediaPlayer.playWAV("/media/ButtonSound.wav"); 
        image.setImage("/media/PizzaCheese.png");
        userList.add(cheeseTypes.get(5));
    }//GEN-LAST:event_btnCheeseParmesanActionPerformed
    /**
     * Adds pizza ingredients to the User Linked List
     * @param evt 
     */
    private void btnTopPeperoniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopPeperoniActionPerformed
        mediaPlayer.playWAV("/media/ButtonSound.wav"); 
        image.setImage("/media/PizzaPeperoni.png");  
        userList.add(toppingTypes.get(0));
    }//GEN-LAST:event_btnTopPeperoniActionPerformed
    /**
     * Adds pizza ingredients to the User Linked List
     * @param evt 
     */
    private void btnTopHamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopHamActionPerformed
        mediaPlayer.playWAV("/media/ButtonSound.wav"); 
        image.setImage("/media/PizzaSalamiAndHam.png");
        userList.add(toppingTypes.get(1));
    }//GEN-LAST:event_btnTopHamActionPerformed
    /**
     * Adds pizza ingredients to the User Linked List
     * @param evt 
     */
    private void btnTopSalamiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopSalamiActionPerformed
        mediaPlayer.playWAV("/media/ButtonSound.wav"); //plays a nice sound on the click of the button
        //from the package media (for future sounds add sounds o the media folder)
        image.setImage("/media/PizzaSalamiAndHam.png");  //sets the picture from the media package
        userList.add(toppingTypes.get(2)); 
    }//GEN-LAST:event_btnTopSalamiActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheeseCheddar;
    private javax.swing.JButton btnCheeseMozz;
    private javax.swing.JButton btnCheeseOld;
    private javax.swing.JButton btnCheeseParmesan;
    private javax.swing.JButton btnCheeseProvolone;
    private javax.swing.JButton btnCheeseSwiss;
    private javax.swing.JButton btnDone;
    private javax.swing.JButton btnDoughCheese;
    private javax.swing.JButton btnDoughFull;
    private javax.swing.JButton btnDoughItalian;
    private javax.swing.JButton btnDoughSoft;
    private javax.swing.JButton btnDoughThick;
    private javax.swing.JButton btnDoughThin;
    private javax.swing.JButton btnSauceAmerican;
    private javax.swing.JButton btnSauceChipotle;
    private javax.swing.JButton btnSauceHomeMade;
    private javax.swing.JButton btnSauceItalian;
    private javax.swing.JButton btnSauceLouisiana;
    private javax.swing.JButton btnSauceSpicy;
    private javax.swing.JButton btnTopHam;
    private javax.swing.JButton btnTopMushroom;
    private javax.swing.JButton btnTopPeperoni;
    private javax.swing.JButton btnTopPepper;
    private javax.swing.JButton btnTopPineApple;
    private javax.swing.JButton btnTopSalami;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblDisMoney;
    private javax.swing.JLabel lblHeart1;
    private javax.swing.JLabel lblHeart2;
    private javax.swing.JLabel lblHeart3;
    private javax.swing.JLabel lblMoney;
    private javax.swing.JLabel lblOrder;
    private javax.swing.JLabel lblPic;
    private javax.swing.JLabel lblResponse;
    private javax.swing.JLabel lblServed;
    private javax.swing.JLabel lblTimer;
    private javax.swing.JLabel lblTxt;
    private javax.swing.JLabel txtName;
    // End of variables declaration//GEN-END:variables
    /**
     * Runs the timer
     * sets the money label
     * checks for the time limit to hit 0
     * Is constantly running
     */
    private void backgroundCheck() {
        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String cash = Integer.toString(money);
                lblDisMoney.setText(cash);
                time--;
                lblTimer.setText(Integer.toString(time));
                if (time == 0) { //checks for the time limit
                    lblResponse.setText("Forget it im leaving");
                    checkTime();
                    money--;
                    lives--;
                    redrawHearts();
                }
            }
        });
    }
    /**
     * Displays the players stats when he looses like amount served and money got
     */
    private void displayStats() {
        JOptionPane.showMessageDialog(null, "Game Over" + "\n"
                + "You have served " + served + " Customers and got " + money + "$");
    }
    /**
     * At the start of the game asks player for name.
     * If null sets automatically a deafult name
     */
    private void name() {
        String name;
        String text = "Welcome to Papa's pizzeria recruit, what shall we call you?";
        name = JOptionPane.showInputDialog(null, text);
        if (name.equals("")) { // make the edge scenario thingy work
            txtName.setText("Newbie"); //secret easter egg //pasta == music change
        } else {
            txtName.setText(name); //sets the label name to the choosen name
        }
    }
    /**
     * Compares the two linked lists (user list and generated order) 
     * uses linkedList equal methods id two are equal money goes up and amount served goes up
     * if not equal lives drop and money drops in addition customer spits out a response to the orders quality
     * Spawns another customer if lives != 0. Also updates the labels
     * @param order the customer generated order to check
     * @param userList the user created linked list to check
     */
    private void checkOrder(LinkedList<String> order, LinkedList<String> userList) {
        if (userList.equals(order)) { //LinkedList method that checks if the 2 lists are equal
            order.finalize(); //cleans the generated order for the customer to reuse
            userList.finalize();//cleans the userList for the next pizza order
            String cash = Integer.toString(money);
            lblOrder.setText(""); // re sets order label
            lblResponse.setText("Thanks this is just what I wanted"); //postive response
            money++;
            served++;
            lblServed.setText("Served: " + served); //updates the served label
            lblDisMoney.setText(cash); //updates the money label with the new amount
            checkTime();
            spawnCustomer();
        } else {
            String cash = Integer.toString(money);
            order.finalize(); //cleans the generated order for the customer to reuse
            userList.finalize(); //cleans the userList for the next pizza order
            lblOrder.setText("");
            lblResponse.setText("Beh, and you call this place a 'Pizzeria'"); //negative response
            lives--;
            money--;
            redrawHearts();
            lblDisMoney.setText(cash); //updates the money label with the new amount
            checkTime();
            spawnCustomer(); 
        }
    }
    /**
     * Is based on the amount of customers served and checks if the time 
     * limit to cook a pizza needs to be reduced to increase the difficulty 
     * for the player
     */
    private void checkTime() {
        if (served >= 10) {
            time = 11;
        }
        else if (served >= 5) {
            time = 21;
        } else {
            time = 26;
        }
    }
    /**
     * Checks if hearts need to be redrawn based on the amount of lives the user still has
     * if his lives decrease one heart goes away each time to a total of 3
     * In addition it writes the end game data to save it in the data.txt file 
     * to later open it in the constructor to read the last score 
     */
    private void redrawHearts() {
        if (lives == 2) {
            lblHeart3.setVisible(false);
        }
        if (lives == 1) {
            lblHeart2.setVisible(false);
        }
        if (lives == 0) {
            lblHeart1.setVisible(false);
            String[] data = {
                "" + money, "" + served
            };
            file.write(data); //writes the score of the last user (
            //customers served and money) to the data.txt file using
            //fileHandler class
            displayStats(); //calls the methods to display the stats
            System.exit(0); //exits the game
        }
    }
    /**
     * Spawns another customer which gives another order to the user to cook
     * keeps spawning customers as long as user doesnt lose the game
     */
    private void spawnCustomer() {
        order = customer.order(doughTypes, sauceTypes, cheeseTypes, toppingTypes);
        lblOrder.setText(order.toString(order));
    }
}
