/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzagame;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author r.stuchevsky
 */
public class UI extends javax.swing.JFrame {

    private int time = 25;
    
    /**
     * Creates new form UI
     */
    public UI() {
       
        setup();
       timer.start();
        this.setVisible(true);
       initComponents();
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblTimer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("order");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 30, 306, 100);

        jLabel2.setText("Picture");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(430, 40, 240, 160);

        jButton1.setText("jButton1");
        getContentPane().add(jButton1);
        jButton1.setBounds(90, 280, 73, 23);

        jButton2.setText("jButton2");
        getContentPane().add(jButton2);
        jButton2.setBounds(90, 320, 73, 23);

        jButton3.setText("jButton3");
        getContentPane().add(jButton3);
        jButton3.setBounds(90, 360, 73, 23);

        jButton4.setText("jButton4");
        getContentPane().add(jButton4);
        jButton4.setBounds(90, 400, 73, 23);

        jButton5.setText("jButton5");
        getContentPane().add(jButton5);
        jButton5.setBounds(90, 440, 73, 23);

        jButton6.setText("jButton6");
        getContentPane().add(jButton6);
        jButton6.setBounds(200, 280, 73, 23);

        jButton7.setText("jButton7");
        getContentPane().add(jButton7);
        jButton7.setBounds(200, 320, 73, 23);

        jButton8.setText("jButton8");
        getContentPane().add(jButton8);
        jButton8.setBounds(200, 360, 73, 23);

        jButton9.setText("jButton9");
        getContentPane().add(jButton9);
        jButton9.setBounds(200, 400, 73, 23);

        jButton10.setText("jButton10");
        getContentPane().add(jButton10);
        jButton10.setBounds(200, 440, 79, 23);

        jButton11.setText("jButton11");
        getContentPane().add(jButton11);
        jButton11.setBounds(320, 280, 79, 23);

        jButton12.setText("jButton12");
        getContentPane().add(jButton12);
        jButton12.setBounds(320, 320, 79, 23);

        jButton13.setText("jButton13");
        getContentPane().add(jButton13);
        jButton13.setBounds(320, 360, 79, 23);

        jButton14.setText("jButton14");
        getContentPane().add(jButton14);
        jButton14.setBounds(320, 400, 79, 23);

        jButton15.setText("jButton15");
        getContentPane().add(jButton15);
        jButton15.setBounds(320, 440, 79, 23);

        jButton16.setText("jButton16");
        getContentPane().add(jButton16);
        jButton16.setBounds(430, 280, 79, 23);

        jButton17.setText("jButton17");
        getContentPane().add(jButton17);
        jButton17.setBounds(430, 320, 79, 23);

        jButton18.setText("jButton18");
        getContentPane().add(jButton18);
        jButton18.setBounds(430, 360, 79, 23);

        jButton19.setText("jButton19");
        getContentPane().add(jButton19);
        jButton19.setBounds(430, 400, 79, 23);

        jButton20.setText("jButton20");
        getContentPane().add(jButton20);
        jButton20.setBounds(430, 440, 79, 23);

        jLabel3.setText("Toppings");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(430, 260, 70, 20);

        jLabel4.setText("Doughs");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 260, 70, 20);

        jLabel5.setText("Sauces");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(200, 260, 70, 20);

        jLabel6.setText("Cheeses");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(320, 260, 70, 20);

        jLabel7.setText("ConfirmText");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 130, 250, 110);

        lblTimer.setText("jLabel8");
        getContentPane().add(lblTimer);
        lblTimer.setBounds(330, 190, 110, 70);
        lblTimer.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private Timer timer;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblTimer;
    // End of variables declaration//GEN-END:variables

    private void setup(){
        
        
        timer = new Timer(1000, new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                time--;
                lblTimer.setText(Integer.toString(time));
                if (time == 0) { 
                    JOptionPane.showMessageDialog(null, "bruh");
                    System.exit(0);
            }
            } //else if order correct reset timer time = 25;
        });
    
    }

}
